-   id: alembic-migrations-validator
    name: alembic-migrations-validator
    entry: alembic-migrations-validator.validator.main
    require_serial: true
    language: python
    types_or: [cython, pyi, python]
#    args: ['--filter-files']  TODO
    minimum_pre_commit_version: '2.9.2'
