[tool.poetry]
name = "alembic-migrations-validator"
version = "0.1.0"
description = ""
authors = ["Moshe-Malka <moshemalka2014@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
